### ISSUE TITLE
Use keycodes npm package instead of in-built array

### ISSUE THREAD

**Issue by artfuldev** [artfuldev/cycle-keyboard#29]
Link to package:
https://www.npmjs.com/package/keycode
- [x] Add dependency
- [x] Use keycode instead of array
- [x] Remove keycodes in-built array

**Comment by Widdershin** [comment]
Why a peer dependency instead of a regular dependency? Doesn't that mean the user will have to install it manually? (At least using npm3)

**Comment by artfuldev** [comment]
If we use a direct dependency we will tie him to a particular version. If he uses a later version of keycode, we will fall behind it unnecessarily.

**Comment by artfuldev** [comment]
This way, we can promise that they will be able to get the same keycodes that their app already uses in other places. What do you say, @Widdershin @raquelxmoss ?

**Comment by Widdershin** [comment]
We can use `greenkeeper` to ensure that our dependencies are up to date. I definitely vote for using a dependency instead of a peerDependency, to save the hassle of the user having to install another package.

Can we also refer to our hypothetical users as they? If we always say 'he' then we get into the mindset of assuming our users are male. Just a minor thing 😄

**Comment by artfuldev** [comment]
Point taken, comment updated.
If we are sure this won't be a problem, we'll switch to a dependency instead.

**Comment by artfuldev** [comment]
Starting work in this branch: https://github.com/cyclejs-community/cycle-keyboard/tree/use-keycodes

**Comment by artfuldev** [comment]
keycodes has no .d.ts file yet, so finding it hard to use... Any advice @Widdershin ?
